# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a1824c9d76334dad029f814d34d8c359c4c89c58089e44bda9de0f13df2e9b78ade3a43c11b24596e3b7e9d0fc81cc4075261cc94c05d93dd5a47c2915fc387

test:
  secret_key_base: f4aaa6816f214ccae6e57877d2264e2cdda733f0de541104bb66f71b56401d353a5dc5c437eee2aeed591ceb11132520283c81c564840c029cda17f049d0b2df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
